name: Security Scans

on:
  push:
    branches:
      - develop
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '**.md'

jobs:
  scans:
    name: Security Scans
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkov Scan
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: "."
          framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
          output_format: json # optional: the output format, one of: cli, json, junitxml, github_failed_only
