name: Security Scans

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '**.md'

jobs:
  go-tests:
    name: Security Scans
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Security Scan
        id: Bridgecrew
        uses: bridgecrewio/bridgecrew-action@master
        with:
          api-key: ${{ secrets.BRIDGECREW_API_KEY }}
          directory: "."
          soft_fail: false
          # BC: "check_name": "X-ray tracing is enabled for Lambda" - disabled
          skip_check: CKV_AWS_50
          output_format: json
