name: Unit Tests

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  go-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7

      - name: Download Go Modules
        working-directory: tests
        run: go mod download

      - name: Set ssh keys for github remote download
        working-directory: tests
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_GITHUB }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check

#      - name: Run Go Tests
#        working-directory: tests
#        run: |
#          go test -v
#        env:
#          # TF ENVIRONMENT
#          TF_AWS_BUCKET: "${{ secrets.TF_NONPROD_AWS_BUCKET }}"
#          TF_AWS_PROFILE: "${{ secrets.TF_AWS_PROFILE }}"
#          TF_AWS_BUCKET_REGION: "${{ secrets.TF_AWS_BUCKET_REGION }}"
#          # AWS CREDENTIALS
#          AWS_ACCESS_KEY_ID: "${{ secrets.DEV_AWS_ACCESS_KEY_ID }}"
#          AWS_SECRET_ACCESS_KEY: "${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}"
