name: Unit Tests

on:
  push:
    branches:
      - main

jobs:
  go-tests:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7

      - name: Download Go Modules
        working-directory: tests
        run: go mod download

#      - name: Security Scan
#        id: Bridgecrew
#        uses: bridgecrewio/bridgecrew-action@master
#        with:
#          api-key: ${{ secrets.BRIDGECREW_API_KEY }}

      - name: Run Go Tests
        working-directory: tests
        run: |
          go test -v
        env:
          # TF ENVIRONMENT
          TF_AWS_BUCKET: "${{ secrets.TF_NONPROD_AWS_BUCKET }}"
          TF_AWS_PROFILE: "${{ secrets.TF_AWS_PROFILE }}"
          TF_AWS_BUCKET_REGION: "${{ secrets.TF_AWS_BUCKET_REGION }}"
          # AWS CREDENTIALS
          AWS_ACCESS_KEY_ID: "${{ secrets.DEV_AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}"
          AWS_SESSION_TOKEN: "${{ secrets.AWS_SESSION_TOKEN }}"
          AWS_SECURITY_TOKEN: "${{ secrets.AWS_SECURITY_TOKEN }}"
